services:
  app:
    build:
      context: .
    env_file:
      - ./config/.env # Ensure this path is correct
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: larssiebig
      POSTGRES_PASSWORD: test12345
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
